#define F_CPU 14745600
#include <avr/io.h>
#include <avr/interrupt.h>
#include <util/delay.h>
#include <avr/eeprom.h>
#include <math.h> //included to support power function
#include "lcd.c"

volatile unsigned long int pulse = 0; //to keep the track of the number of pulses generated by the color sensor
volatile unsigned long int red;       // variable to store the pulse count when read_red function is called
volatile unsigned long int blue;      // variable to store the pulse count when read_blue function is called
volatile unsigned long int green;     // variable to store the pulse count when read_green function is called
volatile unsigned long int ShaftCountLeft = 0; //to keep track of left position encoder
volatile unsigned long int ShaftCountRight = 0; //to keep track of right position encoder
volatile unsigned int Degrees; //to accept angle in degrees for turning
unsigned int value1;
unsigned int value2;
unsigned int value3;
unsigned char sharp1;
unsigned char sharp2;
unsigned char sharp3;
unsigned char ADC_Conversion(unsigned char);
unsigned char ADC_Value;
unsigned char flag = 0;
unsigned char Left_white_line = 0;
unsigned char Center_white_line = 0;
unsigned char Right_white_line = 0;
int a=0;
int s=0;
unsigned char LW = 0;
unsigned char CW = 0;
unsigned char R_W = 0;
unsigned int count=0;
unsigned int threshold_l=18;
unsigned int threshold_c=18;
unsigned int threshold_r=18;
volatile unsigned long int color_detected;
volatile unsigned long int color;
long int threshold_value = 1500;
unsigned int colour_flag;
int room_color[8];   //array to store the color according to room


void lcd_port_config (void)
{
	DDRC = DDRC | 0xF7; //setting all the LCD pin's direction set as output
	PORTC = PORTC & 0x80; //setting all the LCD pins are set to logic 0 except PORTC 7
}
void RGB_LED_config (void)
{
	DDRJ = 0x0F; //setting all the LED pin's direction set as output
	PORTJ =0xFF; //setting all the LED pins are set to logic 0 except PORTB OTHER PIN
}
void motion_pin_config (void)
{
	DDRA = DDRA | 0x0F;
	PORTA = PORTA & 0xF0;
	DDRL = DDRL | 0x18;   //Setting PL3 and PL4 pins as output for PWM generation
	PORTL = PORTL | 0x18; //PL3 and PL4 pins are for velocity control using PWM.
}
void servo1_pin_config (void)
{
 DDRB  = DDRB | 0x20;  //making PORTB 5 pin output
 PORTB = PORTB | 0x20; //setting PORTB 5 pin to logic 1
}

//Configure PORTB 6 pin for servo motor 2 operation
void servo2_pin_config (void)
{
 DDRB  = DDRB | 0x40;  //making PORTB 6 pin output
 PORTB = PORTB | 0x40; //setting PORTB 6 pin to logic 1
}
void timer1_init(void)
{
 TCCR1B = 0x00; //stop
 TCNT1H = 0xFC; //Counter high value to which OCR1xH value is to be compared with
 TCNT1L = 0x01;	//Counter low value to which OCR1xH value is to be compared with
 OCR1AH = 0x03;	//Output compare Register high value for servo 1
 OCR1AL = 0xFF;	//Output Compare Register low Value For servo 1
 OCR1BH = 0x03;	//Output compare Register high value for servo 2
 OCR1BL = 0xFF;	//Output Compare Register low Value For servo 2
 OCR1CH = 0x03;	//Output compare Register high value for servo 3
 OCR1CL = 0xFF;	//Output Compare Register low Value For servo 3
 ICR1H  = 0x03;	
 ICR1L  = 0xFF;
 TCCR1A = 0xAB; /*{COM1A1=1, COM1A0=0; COM1B1=1, COM1B0=0; COM1C1=1 COM1C0=0}
 					For Overriding normal port functionality to OCRnA outputs.
				  {WGM11=1, WGM10=1} Along With WGM12 in TCCR1B for Selecting FAST PWM Mode*/
 TCCR1C = 0x00;
 TCCR1B = 0x0C; //WGM12=1; CS12=1, CS11=0, CS10=0 (Prescaler=256)
}
void adc_pin_config (void)
{
 DDRF = 0x00; 
 PORTF = 0x00;
 DDRK = 0x00;
 PORTK = 0x00;
}
void adc_init()
{
	ADCSRA = 0x00;
	ADCSRB = 0x00;		//MUX5 = 0
	ADMUX = 0x20;		//Vref=5V external --- ADLAR=1 --- MUX4:0 = 0000
	ACSR = 0x80;
	ADCSRA = 0x86;		//ADEN=1 --- ADIE=1 --- ADPS2:0 = 1 1 0
}

//Function For ADC Conversion
unsigned char ADC_Conversion(unsigned char Ch) 
{
	unsigned char a;
	if(Ch>7)
	{
		ADCSRB = 0x08;
	}
	Ch = Ch & 0x07;  			
	ADMUX= 0x20| Ch;	   		
	ADCSRA = ADCSRA | 0x40;		//Set start conversion bit
	while((ADCSRA&0x10)==0);	//Wait for conversion to complete
	a=ADCH;
	ADCSRA = ADCSRA|0x10; //clear ADIF (ADC Interrupt Flag) by writing 1 to it
	ADCSRB = 0x00;
	return a;
}
unsigned int Sharp_GP2D12_estimation(unsigned char adc_reading)
{
	float distance;
	unsigned int distanceInt;
	distance = (int)(10.00*(2799.6*(1.00/(pow(adc_reading,1.1546)))));
	distanceInt = (int)distance;
	if(distanceInt>800)
	{
		distanceInt=800;
	}
	return distanceInt;
}
void timer5_init()
{
	TCCR5B = 0x00;	//Stop
	TCNT5H = 0xFF;	//Counter higher 8-bit value to which OCR5xH value is compared with
	TCNT5L = 0x01;	//Counter lower 8-bit value to which OCR5xH value is compared with
	OCR5AH = 0x00;	//Output compare register high value for Left Motor
	OCR5AL = 0xFF;	//Output compare register low value for Left Motor
	OCR5BH = 0x00;	//Output compare register high value for Right Motor
	OCR5BL = 0xFF;	//Output compare register low value for Right Motor
	OCR5CH = 0x00;	//Output compare register high value for Motor C1
	OCR5CL = 0xFF;	//Output compare register low value for Motor C1
	TCCR5A = 0xA9;	/*{COM5A1=1, COM5A0=0; COM5B1=1, COM5B0=0; COM5C1=1 COM5C0=0}
 					  For Overriding normal port functionality to OCRnA outputs.
				  	  {WGM51=0, WGM50=1} Along With WGM52 in TCCR5B for Selecting FAST PWM 8-bit Mode*/
	
	TCCR5B = 0x0B;	//WGM12=1; CS12=0, CS11=1, CS10=1 (Prescaler=64)
}

// Function for robot velocity control
void velocity (unsigned char left_motor, unsigned char right_motor)
{
	OCR5AL = (unsigned char)left_motor;
	OCR5BL = (unsigned char)right_motor;
}


void left_encoder_pin_config (void)
{
	DDRE  = DDRE & 0xEF;  //Set the direction of the PORTE 4 pin as input
	PORTE = PORTE | 0x10; //Enable internal pull-up for PORTE 4 pin
}

//Function to configure INT5 (PORTE 5) pin as input for the right position encoder
void right_encoder_pin_config (void)
{
	DDRE  = DDRE & 0xDF;  //Set the direction of the PORTE 4 pin as input
	PORTE = PORTE | 0x20; //Enable internal pull-up for PORTE 4 pin
}
void left_position_encoder_interrupt_init (void) //Interrupt 4 enable
{
	cli(); //Clears the global interrupt
	EICRB = EICRB | 0x02; // INT4 is set to trigger with falling edge
	EIMSK = EIMSK | 0x10; // Enable Interrupt INT4 for left position encoder
	sei();   // Enables the global interrupt
}

void right_position_encoder_interrupt_init (void) //Interrupt 5 enable
{
	cli(); //Clears the global interrupt
	EICRB = EICRB | 0x08; // INT5 is set to trigger with falling edge
	EIMSK = EIMSK | 0x20; // Enable Interrupt INT5 for right position encoder
	sei();   // Enables the global interrupt
}

//ISR for right position encoder
ISR(INT5_vect)
{
	ShaftCountRight++;  //increment right shaft position count
}


//ISR for left position encoder
ISR(INT4_vect)
{
	ShaftCountLeft++;  //increment left shaft position count
}

void color_sensor_pin_config(void)
{
	DDRD  = DDRD | 0xFE; //set PD0 as input for color sensor output
	PORTD = PORTD | 0x01;//Enable internal pull-up for PORTD 0 pin
}

void port_init(void)
{
	lcd_port_config();//lcd pin configuration
	color_sensor_pin_config();//color sensor pin configuration
	motion_pin_config(); //robot motion pins config
	left_encoder_pin_config(); //left encoder pin config
	right_encoder_pin_config(); //right encoder pin config
	servo1_pin_config();
	servo2_pin_config();
	adc_pin_config();

}
void servo_1(unsigned char degrees)  
{
 float PositionPanServo = 0;
  PositionPanServo = ((float)degrees / 1.86) + 35.0;
 OCR1AH = 0x00;
 OCR1AL = (unsigned char) PositionPanServo;
}


//Function to rotate Servo 2 by a specified angle in the multiples of 1.86 degrees
void servo_2(unsigned char degrees)
{
 float PositionTiltServo = 0;
 PositionTiltServo = ((float)degrees / 1.86) + 35.0;
 OCR1BH = 0x00;
 OCR1BL = (unsigned char) PositionTiltServo;
}

void color_sensor_pin_interrupt_init(void) //Interrupt 0 enable
{
	cli(); //Clears the global interrupt
	EICRA = EICRA | 0x02; // INT0 is set to trigger with falling edge
	EIMSK = EIMSK | 0x01; // Enable Interrupt INT0 for color sensor
	sei(); // Enables the global interrupt
}

//ISR for color sensor
ISR(INT0_vect)
{
	pulse++; //increment on receiving pulse from the color sensor
}
void motion_set (unsigned char Direction)
{
	unsigned char PortARestore = 0;

	Direction &= 0x0F; 		// removing upper nibbel for the protection
	PortARestore = PORTA; 		// reading the PORTA original status
	PortARestore &= 0xF0; 		// making lower direction nibbel to 0
	PortARestore |= Direction; // adding lower nibbel for forward command and restoring the PORTA status
	PORTA = PortARestore; 		// executing the command
}
void forward (void) //both wheels forward
{
	motion_set(0x06);
}

void back (void) //both wheels backward
{
	motion_set(0x09);
}

void left (void) //Left wheel backward, Right wheel forward
{
	motion_set(0x05);
}

void right (void) //Left wheel forward, Right wheel backward
{
	motion_set(0x0A);
}

void stop (void)
{
	motion_set(0x00);
}
void soft_left (void) //Left wheel stationary, Right wheel forward
{
	motion_set(0x04);
}

void soft_right (void) //Left wheel forward, Right wheel is stationary
{
	motion_set(0x02);
}
void soft_left_degrees(unsigned int Degrees)
{
	// 176 pulses for 360 degrees rotation 2.045 degrees per count
	soft_left(); //Turn soft left
	Degrees=Degrees*2;
	angle_rotate(Degrees);
}

void soft_right_degrees(unsigned int Degrees)
{
	// 176 pulses for 360 degrees rotation 2.045 degrees per count
	soft_right();  //Turn soft right
	Degrees=Degrees*2;
	angle_rotate(Degrees);
}

void red_detect()
{
	PORTJ = 0x06;
} 
void green_detect()
{
	PORTJ = 0x05;
}
void blue_detect()
{
	PORTJ =0x03;
}
void angle_rotate(unsigned int Degrees)
{
	float ReqdShaftCount = 0;
	unsigned long int ReqdShaftCountInt = 0;

	ReqdShaftCount = (float) Degrees/ 4.090; // division by resolution to get shaft count
	ReqdShaftCountInt = (unsigned int) ReqdShaftCount;
	ShaftCountRight = 0;
	ShaftCountLeft = 0;

	while (1)
	{
		if((ShaftCountRight >= ReqdShaftCountInt) | (ShaftCountLeft >= ReqdShaftCountInt))
		break;
	}
	stop(); //Stop robot
}

//Function used for moving robot forward by specified distance

void linear_distance_mm(unsigned int DistanceInMM)
{
	float ReqdShaftCount = 0;
	unsigned long int ReqdShaftCountInt = 0;

	ReqdShaftCount = DistanceInMM / 5.338; // division by resolution to get shaft count
	ReqdShaftCountInt = (unsigned long int) ReqdShaftCount;
	
	ShaftCountRight = 0;
	while(1)
	{
		if(ShaftCountRight > ReqdShaftCountInt)
		{
			break;
		}
	}
	stop(); //Stop robot
}
void forward_mm(unsigned int DistanceInMM)
{
	forward();
	linear_distance_mm(DistanceInMM);
}

void back_mm(unsigned int DistanceInMM)
{
	back();
	linear_distance_mm(DistanceInMM);
}

void left_degrees(unsigned int Degrees)
{
	// 88 pulses for 360 degrees rotation 4.090 degrees per count
	left(); //Turn left
	angle_rotate(Degrees);
}



void right_degrees(unsigned int Degrees)
{
	// 88 pulses for 360 degrees rotation 4.090 degrees per count
	right(); //Turn right
	angle_rotate(Degrees);
}

void init_devices(void)
{
	cli(); //Clears the global interrupt
	color_sensor_pin_interrupt_init();
	left_position_encoder_interrupt_init();
	right_position_encoder_interrupt_init();
	timer5_init();
	timer1_init();
	adc_init();
	sei();   // Enables the global interrupt
}

//Filter Selection
void filter_red(void)    //Used to select red filter
{
	//Filter Select - red filter
	PORTD = PORTD & 0xBF; //set S2 low
	PORTD = PORTD & 0x7F; //set S3 low
}

void filter_green(void)	//Used to select green filter
{
	//Filter Select - green filter
	PORTD = PORTD | 0x40; //set S2 High
	PORTD = PORTD | 0x80; //set S3 High
}

void filter_blue(void)	//Used to select blue filter
{
	//Filter Select - blue filter
	PORTD = PORTD & 0xBF; //set S2 low
	PORTD = PORTD | 0x80; //set S3 High
}

void filter_clear(void)	//select no filter
{
	//Filter Select - no filter
	PORTD = PORTD | 0x40; //set S2 High
	PORTD = PORTD & 0x7F; //set S3 Low
}

//Color Sensing Scaling
void color_sensor_scaling()		//This function is used to select the scaled down version of the original frequency of the output generated by the color sensor, generally 20% scaling is preferable, though you can change the values as per your application by referring datasheet
{
	//Output Scaling 20% from datasheet
	//PORTD = PORTD & 0xEF;
	PORTD = PORTD | 0x10; //set S0 high
	//PORTD = PORTD & 0xDF; //set S1 low
	PORTD = PORTD | 0x20; //set S1 high
}

void red_read(void) // function to select red filter and display the count generated by the sensor on LCD. The count will be more if the color is red. The count will be very less if its blue or green.
{
	//Red
	filter_red(); //select red filter
	pulse=0; //reset the count to 0
	_delay_ms(100); //capture the pulses for 100 ms or 0.1 second
	red = (pulse-1200);  //store the count in variable called red
	
	/*lcd_cursor(1,1);  //set the cursor on row 1, column 1
	lcd_string("Red Pulses"); // Display "Red Pulses" on LCD
	lcd_print(2,1,red,5);  //Print the count on second row
	_delay_ms(1000);	// Display for 1000ms or 1 second
	lcd_wr_command(0x01); //Clear the LCD
	*/
}

void green_read(void) // function to select green filter and display the count generated by the sensor on LCD. The count will be more if the color is green. The count will be very less if its blue or red.
{
	//Green
	filter_green(); //select green filter
	pulse=0; //reset the count to 0
	_delay_ms(100); //capture the pulses for 100 ms or 0.1 second
	green = pulse;  //store the count in variable called green
	
	/*lcd_cursor(1,1);  //set the cursor on row 1, column 1
	lcd_string("Green Pulses"); // Display "Green Pulses" on LCD
	lcd_print(2,1,green,5);  //Print the count on second row
	_delay_ms(1000);	// Display for 1000ms or 1 second
	lcd_wr_command(0x01); //Clear the LCD
	*/
}

void blue_read(void) // function to select blue filter and display the count generated by the sensor on LCD. The count will be more if the color is blue. The count will be very less if its red or green.
{
	//Blue
	filter_blue(); //select blue filter
	pulse=0; //reset the count to 0
	_delay_ms(100); //capture the pulses for 100 ms or 0.1 second
	blue = pulse;  //store the count in variable called blue
	
	/*lcd_cursor(1,1);  //set the cursor on row 1, column 1
	lcd_string("Blue Pulses"); // Display "Blue Pulses" on LCD
	lcd_print(2,1,blue,5);  //Print the count on second row
	_delay_ms(1000);	// Display for 1000ms or 1 second
	lcd_wr_command(0x01); //Clear the LCD
	*/
}
unsigned int color_detection()
{
		red_read(); //display the pulse count when red filter is selected
	   _delay_ms(100);
	   green_read(); //display the pulse count when green filter is selected
	   _delay_ms(100);
	   blue_read(); //display the pulse count when blue filter is selected
	   _delay_ms(100);
	color=red>green?(red>blue?red:blue):(green>blue?green:blue); // logic for getting the greatest value between red, green, blue pulses
	
	if(color>threshold_value)   // condition for checking the color is greater than threshold value for color sensor 
	{
		color_detected=color;
		if(color_detected==red)
		a=1;                     // when color_detected is equals to red x=1 (1 for red)
		else if(color_detected==blue)
		a=2;                     // when color_detected is equals to green x=2 (2 for green)
		else                     
		a=3;                     // when color_detected is equals to red x=3 (3 for blue)
	}
	else if((red<1200)&&(blue<1200)&&(green<1200))
	{                        // condition when color is smaller 
	a=4; 
	}                       // when value of color is less than threshold value  x=4 (4 for black)
	return a;                   // return the value of x
}
void read_values()
{
	
		Left_white_line = ADC_Conversion(3);
		Center_white_line = ADC_Conversion(2);
		Right_white_line = ADC_Conversion(1);
	
}
void linear_distance_mm_follow(unsigned int DistanceInMM)
{
	float ReqdShaftCount = 0;
	unsigned long int ReqdShaftCountInt = 0;

	ReqdShaftCount = DistanceInMM / 5.338; // division by resolution to get shaft count
	ReqdShaftCountInt = (unsigned long int) ReqdShaftCount;
	
	ShaftCountRight = 0;
	while(1)
	{
		if(ShaftCountRight > ReqdShaftCountInt)
		{
			break;
		}
		flag=0;
		read_values();
		if(Center_white_line>threshold_c)
		{
			flag=1;
			forward();
		}
		if(Left_white_line>threshold_l && flag == 0)
		{
			flag=1;
			left();
			while(Center_white_line<threshold_c)
			Center_white_line=ADC_Conversion(2);
		}
		if(Right_white_line>threshold_r && flag == 0)
		{
			flag=1;
			right();
			while(Center_white_line<threshold_c)
			Center_white_line=ADC_Conversion(2);
		}
		else
		forward();
	}
	stop(); //Stop robot
}

void forward_mm_follow(unsigned int DistanceInMM)
{
	forward();
	linear_distance_mm_follow(DistanceInMM);
}


void left_90()
{
	stop();
	left_degrees(40);
	left();
	Center_white_line=ADC_Conversion(2);
	while(Center_white_line<50)
	Center_white_line=ADC_Conversion(2);
	stop();
	soft_left_degrees(5);
	//back_mm(30);
}

void right_90()
{
	stop();
	right_degrees(40);
	right();
	Center_white_line=ADC_Conversion(2);
	while(Center_white_line<50)
	Center_white_line=ADC_Conversion(2);
	stop();
	soft_right_degrees(5);
	//back_mm(30);
}


void right_180()
{
	forward_mm_follow(10);
	stop();
	right_degrees(120);
	right();
	Center_white_line=ADC_Conversion(2);
	while(Center_white_line<50)
	Center_white_line=ADC_Conversion(2);
	stop();
	soft_right_degrees(5);
	//back_mm(30);
}

void black_line_backward()
{
if(Center_white_line>0x28)
		{
			flag=1;
			back();
			velocity(150,150);
		}

		if((Left_white_line<0x28) && (flag==0))
		{
			flag=1;
			back();
			velocity(130,50);
		}

		if((Right_white_line<0x28) && (flag==0))
		{
			flag=1;
			back();
			velocity(50,130);
		}

		if(Center_white_line<0x28 && Left_white_line<0x28 && Right_white_line<0x28)
		{
			back();
			velocity(0,0);
		}



}
void line_follow_forward(void)
	{
		sharp2 = ADC_Conversion(13);
		value2 = Sharp_GP2D12_estimation(sharp2);
		lcd_print(1,2,value2,3);
		sharp1 = ADC_Conversion(9);						//Stores the Analog value of front sharp connected to ADC channel 11 into variable "sharp"
		value1 = Sharp_GP2D12_estimation(sharp1);

		Left_white_line = ADC_Conversion(3);	//Getting data of Left WL Sensor
		Center_white_line = ADC_Conversion(2);	//Getting data of Center WL Sensor
		Right_white_line = ADC_Conversion(1);	//Getting data of Right WL Sensor
		lcd_print(2,1,Left_white_line,3);
		lcd_print(2,5,Center_white_line,3);
		lcd_print(2,9,Right_white_line,3);
		//front_sensor=  ADC_Conversion(11);		//Getting data of front sensor
		flag=0;
		unsigned int count=0;
//		print_sensor(1,1,3);	//Prints value of White Line Sensor1
//		print_sensor(1,5,2);	//Prints Value of White Line Sensor2
//		print_sensor(1,9,1);	//Prints Value of White Line Sensor3
//		print_sensor(2,5,11);	//Prints Value of front sensor
        // for black line value is approx 150 and for white value is approx 12
		lcd_print(1,1,count,2);
		if(Center_white_line>11 && Left_white_line<11 && Right_white_line<11) // only center white line sensor is on black
		{
			flag=1;
			forward();
			velocity(252,254);
		}

		if((Center_white_line<11 && Left_white_line>11 && Right_white_line<11) && (flag==0)) // only left white line sensor is on black
		{
			flag=1;
			forward();
			velocity(200,250);
		}

		if((Center_white_line<11 && Left_white_line<11 && Right_white_line>11) && (flag==0))  // only right white line sensor is on black
		{
			flag=1;
			forward();
			velocity(250,200);
		}
         	if(Center_white_line>11 && Left_white_line>11 && Right_white_line>11) // all are on black
		{ 
			//forward();
			//velocity(255,255);
			count++;
			forward_mm(10);
			stop();
			_delay_ms(100);
			
			
	   	 }

		if(Center_white_line<0x19 && Left_white_line<0x19 && Right_white_line<0x19) //all are on white
		{
			forward();
			velocity(252,254);
		}
		if((Center_white_line<0x19 && Left_white_line<0x19 && Right_white_line<0x19)&&(value1<300||value2<300)) //all are on white
		{
			stop();
			//velocity(252,254);
		}
		if(Center_white_line>11 && Left_white_line<11 && Right_white_line>11) //when center & right are on 
		{
			forward();
			velocity(150,250);
		}
		if(Center_white_line>11 && Left_white_line>11 && Right_white_line<11) // when center and left are on black
		{
			forward();
			velocity(250,150);
		}

	
	}
	void line_follow_backward(void)
	{
		sharp2 = ADC_Conversion(13);
		value2 = Sharp_GP2D12_estimation(sharp2);
		lcd_print(1,2,value2,3);
		sharp1 = ADC_Conversion(9);						//Stores the Analog value of front sharp connected to ADC channel 11 into variable "sharp"
		value1 = Sharp_GP2D12_estimation(sharp1);

		Left_white_line = ADC_Conversion(3);	//Getting data of Left WL Sensor
		Center_white_line = ADC_Conversion(2);	//Getting data of Center WL Sensor
		Right_white_line = ADC_Conversion(1);	//Getting data of Right WL Sensor
		lcd_print(2,1,Left_white_line,3);
		lcd_print(2,5,Center_white_line,3);
		lcd_print(2,9,Right_white_line,3);
		//front_sensor=  ADC_Conversion(11);		//Getting data of front sensor
		flag=0;
		unsigned int count=0;
		//		print_sensor(1,1,3);	//Prints value of White Line Sensor1
		//		print_sensor(1,5,2);	//Prints Value of White Line Sensor2
		//		print_sensor(1,9,1);	//Prints Value of White Line Sensor3
		//		print_sensor(2,5,11);	//Prints Value of front sensor
		// for black line value is approx 150 and for white value is approx 12
		lcd_print(1,1,count,2);
		if(Center_white_line>11 && Left_white_line<11 && Right_white_line<11) // only center white line sensor is on black
		{
			flag=1;
			back();
			velocity(252,254);
		}

		if((Center_white_line<11 && Left_white_line>11 && Right_white_line<11) && (flag==0)) // only left white line sensor is on black
		{
			flag=1;
			back();
			velocity(250,200);
		}

		if((Center_white_line<11 && Left_white_line<11 && Right_white_line>11) && (flag==0))  // only right white line sensor is on black
		{
			flag=1;
			back();
			velocity(200,250);
		}
		if(Center_white_line>11 && Left_white_line>11 && Right_white_line>11) // all are on black
		{
			//back();
			//velocity(255,0);
			count++;
			forward_mm(5);
			stop();
			_delay_ms(100);
			
			
		}

		if(Center_white_line<0x19 && Left_white_line<0x19 && Right_white_line<0x19) //all are on white
		{
			back();
			velocity(252,254);
		}
		if((Center_white_line<0x19 && Left_white_line<0x19 && Right_white_line<0x19)&&(value1<300||value2<300)) //all are on white
		{
			stop();
			//velocity(252,254);
		}
		if(Center_white_line>11 && Left_white_line<11 && Right_white_line>11) //when center & right are on
		{
			back();
			velocity(0,250);
		}
		if(Center_white_line>11 && Left_white_line>11 && Right_white_line<11) // when center and left are on black
		{
			back();
			velocity(0,250);
		}

		
	}

	
void led_glow(unsigned int s)
{
	int p=1;
	if ((room_color[s]==1)&&(p==1))
	{
		red_detect();
		_delay_ms(100);
		p=p+1;
	}
	if((room_color[s]==2) &&(p==1))
	{
		blue_detect();
		_delay_ms(100);
		p=p+1;
	}
	if((room_color[s]==3)&&(p==1))
	{
		green_detect();
		_delay_ms(100);
		p=p+1;
	}
	else if(p==1)
	{
		PORTJ=0x07;
	}
}
room_array()
{
		room_color[s]=color_detection();
		led_glow(s);
		_delay_ms(500);
		s=s+1;
}
void servo_grab()
{
for (i = 10; i<=60; i++)
{
	servo_1(i);
	_delay_ms(30);
	
}

}
void straight_forward()
{
	sharp2 = ADC_Conversion(13);
	value2 = Sharp_GP2D12_estimation(sharp2);
	lcd_print(1,2,value2,3);
	sharp1 = ADC_Conversion(9);						//Stores the Analog value of front sharp connected to ADC channel 11 into variable "sharp"
	value1 = Sharp_GP2D12_estimation(sharp1);
	lcd_print(2,6,value1,3);
	sharp3 = ADC_Conversion(11);
	value3 = Sharp_GP2D12_estimation(sharp3);
	lcd_print(1,10,value3,3);
	
	read_values();
	if ((Left_white_line>15)||(Right_white_line>15)||(Center_white_line>15))
	{
		green_service();
	}
		if((value1 < 110)||(value2 < 110))
		
		{
		forward();
		velocity(200,255);	
		}
		else if(sharp1==sharp2)
		{
			forward();
			velocity(250,250);
		}
		else if(sharp1 < sharp2)
		{
			forward ();
			velocity(200,250);
		}
		else if(sharp1 > sharp2)
		{
			forward ();
			velocity(250,220);
		}
	}	
	
void straight_backward()
	{
		sharp2 = ADC_Conversion(13);
		value2 = Sharp_GP2D12_estimation(sharp2);
		lcd_print(1,2,value2,3);
		sharp1 = ADC_Conversion(9);						//Stores the Analog value of front sharp connected to ADC channel 11 into variable "sharp"
		value1 = Sharp_GP2D12_estimation(sharp1);
		//sharp3 = ADC_Conversion(11);
		//value3 = Sharp_GP2D12_estimation(sharp3);
		lcd_print(1,6,value1,3);
		if((value1< 250)&& (value2<250))
		{
			if((value1 < 115)||(value2 < 115))
			
			{
				back();
				velocity(200,255);
			}
			if(sharp1==sharp2)
			{
				back();
				velocity(250,250);
			}
			if(sharp1 < sharp2)
			{
				back ();
				velocity(250,220);
			}
			if(sharp1 > sharp2)
			{
				back ();
				velocity(220,250);
			}
		}
	}
void mapping_arena()
{
	while(1)
	{
	flag=0;
		while(value3 > 120 )
	{
		
		if (flag==0)
		{
			stop();
			_delay_ms(500);
			left_degrees(10);
			//red_detect();
				room_array();
			//_delay_ms(500);
			//led_glow();
			//lcd_wr_command(1);
			
			right_degrees(10);
			flag=flag+1;
		}
		
		
		sharp3 = ADC_Conversion(11);
		value3 = Sharp_GP2D12_estimation(sharp3);
		
		//_delay_ms(100);
		if (value3 < 120)
		{
	
			break;
		}
		straight_forward();
		
	}
	//lcd_wr_command(1);
	if(flag==1)
	{
		stop();
		_delay_ms(100);
		left_degrees(10);
		room_array();
		
		//red_detect();
		//_delay_ms(500);
		//led_glow();
		right_degrees(10);
		flag=flag+1;
		
	}
	
	straight_backward();
	if((value1>500)||(value2>500))//&&(flag==3))
	{
		stop();
		_delay_ms(100);
		/*Center_white_line = ADC_Conversion(2);
		if(Center_white_line>13);
		{
			Center_white_line = ADC_Conversion(2);
			line_follow_backward();
			
		}*/
		back_mm(90);
		_delay_ms(100);
		right_degrees(80);
		for (int i=0;i<4000;i++)
		{
			LW = ADC_Conversion(3); //Getting data of Left WL Sensor
			CW = ADC_Conversion(2); //Getting data of Center WL Sensor
			R_W = ADC_Conversion(1); //Getting data of Right WL Sensor
			
			right();
			velocity(200,200);
			if(CW>=20)
			break;
		}
		_delay_ms(100);
		forward_mm_follow(200);
		_delay_ms(100);
		for(int i=0;i<5;i++)
		{
			sharp3 = ADC_Conversion(11);
			value3 = Sharp_GP2D12_estimation(sharp3);
		}
		_delay_ms(500);
	}
	}
}	
void line_follow()
{
	//dynamic();
	while(1)
	{
		flag=0;
		read_values();
		if((Center_white_line>50 && Left_white_line>50) || (Center_white_line>50 && Right_white_line>50 ))
		{
			forward_mm(10);
			count+=1;
			break;
		}
		if(Center_white_line>threshold_c)
		{
			flag=1;
			forward();
		}
		if(Left_white_line>threshold_l && flag == 0)
		{
			flag=1;
			left();
			while(Center_white_line<threshold_c)
			Center_white_line=ADC_Conversion(2);
		}
		if(Right_white_line>threshold_r && flag == 0)
		{
			flag=1;
			right();
			while(Center_white_line<threshold_c)
			Center_white_line=ADC_Conversion(2);
		}
		else
		forward();
	}
	stop();
}
	void right_side_service()
	{
		while(1)
		{
			
		
	if(count==0)
	{
		read_values();
		line_follow();
	}
	 if(count==1)
	 {
		 forward_mm(50);
		 stop();
		 _delay_ms(100);
		 right_degrees(90);
		 /*for (int i=0;i<4000;i++)
		 {
			 LW = ADC_Conversion(3); //Getting data of Left WL Sensor
			 CW = ADC_Conversion(2); //Getting data of Center WL Sensor
			 R_W = ADC_Conversion(1); //Getting data of Right WL Sensor
			 
			 right();
			 velocity(200,200);
			 if(CW>=20)
			 break;
		 }*/
		 //back_mm(30);
		 line_follow();
	 }			
	 if(count==2)
	 {
		 forward_mm(60);
		 stop();
		 _delay_ms(100);
		 left_degrees(85);
		 for (int i=0;i<4000;i++)
		 {
			 LW = ADC_Conversion(3); //Getting data of Left WL Sensor
			 CW = ADC_Conversion(2); //Getting data of Center WL Sensor
			 R_W = ADC_Conversion(1); //Getting data of Right WL Sensor
			 
			 left();
			 velocity(200,200);
			 if(CW>=20)
			 break;
		 }
		 //back_mm(30);
		 line_follow();
	 }
	 if(count==3)
	 {
		 forward_mm(50);
		 stop();
		 _delay_ms(100);
		 right_degrees(90);
		 for (int i=0;i<4000;i++)
		 {
			 LW = ADC_Conversion(3); //Getting data of Left WL Sensor
			 CW = ADC_Conversion(2); //Getting data of Center WL Sensor
			 R_W = ADC_Conversion(1); //Getting data of Right WL Sensor
			 
			 right();
			 velocity(200,200);
			 if(CW>=20)
			 break;
		 }
		 //back_mm(30);
		 forward_mm_follow(120);
		 green_detect();
		 left_degrees(170);
		 for (int i=0;i<4000;i++)
		 {
			 LW = ADC_Conversion(3); //Getting data of Left WL Sensor
			 CW = ADC_Conversion(2); //Getting data of Center WL Sensor
			 R_W = ADC_Conversion(1); //Getting data of Right WL Sensor
			 
			 left();
			 velocity(200,200);
			 if(CW>=20)
			 break;
		 }
		 line_follow();
		 
	 }
	 if(count==4)
	 {
		 forward_mm(50);
		 stop();
		 _delay_ms(100);
		 left_degrees(90);
		 for (int i=0;i<4000;i++)
		 {
			 LW = ADC_Conversion(3); //Getting data of Left WL Sensor
			 CW = ADC_Conversion(2); //Getting data of Center WL Sensor
			 R_W = ADC_Conversion(1); //Getting data of Right WL Sensor
			 
			 left();
			 velocity(200,200);
			 if(CW>=20)
			 break;
		 }
		 //back_mm(30);
		 line_follow();
	 }
	 if(count==5)
	 {
		 forward_mm(50);
		 stop();
		 _delay_ms(100);
		 left_degrees(5);
		 for (int i=0;i<4000;i++)
		 {
			 LW = ADC_Conversion(3); //Getting data of Left WL Sensor
			 CW = ADC_Conversion(2); //Getting data of Center WL Sensor
			 R_W = ADC_Conversion(1); //Getting data of Right WL Sensor
			 
			 left();
			 velocity(200,200);
			 if(CW>=20)
			 break;
		 }
		 //back_mm(30);
		 //forward_mm(50);
		 line_follow();
	 }
	 if(count==6)
	 {
		 forward_mm(50);
		 stop();
		 _delay_ms(100);
		 left_degrees(90);
		 for (int i=0;i<4000;i++)
		 {
			 LW = ADC_Conversion(3); //Getting data of Left WL Sensor
			 CW = ADC_Conversion(2); //Getting data of Center WL Sensor
			 R_W = ADC_Conversion(1); //Getting data of Right WL Sensor
			 
			 left();
			 velocity(200,200);
			 if(CW>=20)
			 break;
		 }
		 //back_mm(30);
		 forward_mm_follow(120);
		 green_detect();
		 left_degrees(170);
		 for (int i=0;i<4000;i++)
		 {
			 LW = ADC_Conversion(3); //Getting data of Left WL Sensor
			 CW = ADC_Conversion(2); //Getting data of Center WL Sensor
			 R_W = ADC_Conversion(1); //Getting data of Right WL Sensor
			 
			 left();
			 velocity(200,200);
			 if(CW>=20)
			 break;
		 }
		 line_follow();
		 
	 }
	 	 
	 
 if(count==7)
 {
	 forward_mm(50);
	 stop();
	 _delay_ms(100);
	 right_degrees(90);
	 for (int i=0;i<4000;i++)
	 {
		 LW = ADC_Conversion(3); //Getting data of Left WL Sensor
		 CW = ADC_Conversion(2); //Getting data of Center WL Sensor
		 R_W = ADC_Conversion(1); //Getting data of Right WL Sensor
		 
		 right();
		 velocity(200,200);
		 if(CW>=20)
		 break;
	 }
	 line_follow();
}
if(count==8)
{
	forward_mm(50);
	stop();
	_delay_ms(100);
	left_degrees(80);
	for (int i=0;i<4000;i++)
	{
		LW = ADC_Conversion(3); //Getting data of Left WL Sensor
		CW = ADC_Conversion(2); //Getting data of Center WL Sensor
		R_W = ADC_Conversion(1); //Getting data of Right WL Sensor
		
		left();
		velocity(200,200);
		if(CW>=20)
		break;
	}
	line_follow();
}	
		
	if(count==9)
	{
		forward_mm(50);
		line_follow();
		/*_delay_ms(100);
		left_degrees(90);
		for (int i=0;i<4000;i++)
		{
			LW = ADC_Conversion(3); //Getting data of Left WL Sensor
			CW = ADC_Conversion(2); //Getting data of Center WL Sensor
			R_W = ADC_Conversion(1); //Getting data of Right WL Sensor
			
			left();
			velocity(200,200);
			if(CW>=20)
			break;
		}*/
		
		}	
	 if(count==10)
	 {
		 forward_mm(60);
		 stop();
		 _delay_ms(100);
		 left_degrees(85);
		 for (int i=0;i<4000;i++)
		 {
			 LW = ADC_Conversion(3); //Getting data of Left WL Sensor
			 CW = ADC_Conversion(2); //Getting data of Center WL Sensor
			 R_W = ADC_Conversion(1); //Getting data of Right WL Sensor
			 
			 left();
			 velocity(200,200);
			 if(CW>=20)
			 break;
		 }
		 //back_mm(30);
		 line_follow();
	 }
	 if(count==11)
	 {
		 forward_mm(50);
		 stop();
		 _delay_ms(100);
		 right_degrees(85);
		 for (int i=0;i<4000;i++)
		 {
			 LW = ADC_Conversion(3); //Getting data of Left WL Sensor
			 CW = ADC_Conversion(2); //Getting data of Center WL Sensor
			 R_W = ADC_Conversion(1); //Getting data of Right WL Sensor
			 
			 right();
			 velocity(200,200);
			 if(CW>=20)
			 break;
		 }
		 //back_mm(30);
		 forward_mm_follow(120);
		 green_detect();
		 left_degrees(170);
		 for (int i=0;i<4000;i++)
		 {
			 LW = ADC_Conversion(3); //Getting data of Left WL Sensor
			 CW = ADC_Conversion(2); //Getting data of Center WL Sensor
			 R_W = ADC_Conversion(1); //Getting data of Right WL Sensor
			 
			 left();
			 velocity(200,200);
			 if(CW>=20)
			 break;
		 }
		 line_follow();
		 
	 }
	 if(count==12)
	 {
		 forward_mm(50);
		 stop();
		 _delay_ms(100);
		 left_degrees(90);
		 for (int i=0;i<4000;i++)
		 {
			 LW = ADC_Conversion(3); //Getting data of Left WL Sensor
			 CW = ADC_Conversion(2); //Getting data of Center WL Sensor
			 R_W = ADC_Conversion(1); //Getting data of Right WL Sensor
			 
			 left();
			 velocity(200,200);
			 if(CW>=20)
			 break;
		 }
		 //back_mm(30);
		 line_follow();
	 }
	 if(count==13)
	 {
		 forward_mm(50);
		 stop();
		 _delay_ms(100);
		 left_degrees(5);
		 for (int i=0;i<4000;i++)
		 {
			 LW = ADC_Conversion(3); //Getting data of Left WL Sensor
			 CW = ADC_Conversion(2); //Getting data of Center WL Sensor
			 R_W = ADC_Conversion(1); //Getting data of Right WL Sensor
			 
			 left();
			 velocity(200,200);
			 if(CW>=20)
			 break;
		 }
		 //back_mm(30);
		 //forward_mm(50);
		 line_follow();
	 }
	 if(count==14)
	 {
		 forward_mm(50);
		 stop();
		 _delay_ms(100);
		 left_degrees(90);
		 for (int i=0;i<4000;i++)
		 {
			 LW = ADC_Conversion(3); //Getting data of Left WL Sensor
			 CW = ADC_Conversion(2); //Getting data of Center WL Sensor
			 R_W = ADC_Conversion(1); //Getting data of Right WL Sensor
			 
			 left();
			 velocity(200,200);
			 if(CW>=20)
			 break;
		 }
		 //back_mm(30);
		 forward_mm_follow(120);
		 green_detect();
		 left_degrees(170);
		 for (int i=0;i<4000;i++)
		 {
			 LW = ADC_Conversion(3); //Getting data of Left WL Sensor
			 CW = ADC_Conversion(2); //Getting data of Center WL Sensor
			 R_W = ADC_Conversion(1); //Getting data of Right WL Sensor
			 
			 left();
			 velocity(200,200);
			 if(CW>=20)
			 break;
		 }
		 line_follow();
		 
	 }
	 
 if(count==15)
 {
	 forward_mm(50);
	 stop();
	 _delay_ms(100);
	 right_degrees(90);
	 for (int i=0;i<4000;i++)
	 {
		 LW = ADC_Conversion(3); //Getting data of Left WL Sensor
		 CW = ADC_Conversion(2); //Getting data of Center WL Sensor
		 R_W = ADC_Conversion(1); //Getting data of Right WL Sensor
		 
		 right();
		 velocity(200,200);
		 if(CW>=20)
		 break;
	 }
	 line_follow();
}
if(count==16)
{
	forward_mm(50);
	stop();
	_delay_ms(100);
	left_degrees(80);
	for (int i=0;i<4000;i++)
	{
		LW = ADC_Conversion(3); //Getting data of Left WL Sensor
		CW = ADC_Conversion(2); //Getting data of Center WL Sensor
		R_W = ADC_Conversion(1); //Getting data of Right WL Sensor
		
		left();
		velocity(200,200);
		if(CW>=20)
		break;
	}
	line_follow();
}	
		
	if(count==17)
	{
		forward_mm(50);
		stop();
		break;
		/*_delay_ms(100);
		left_degrees(90);
		for (int i=0;i<4000;i++)
		{
			LW = ADC_Conversion(3); //Getting data of Left WL Sensor
			CW = ADC_Conversion(2); //Getting data of Center WL Sensor
			R_W = ADC_Conversion(1); //Getting data of Right WL Sensor
			
			left();
			velocity(200,200);
			if(CW>=20)
			break;
		}*/
	

		}
}
}
void green_service()
{
	if(count==0)
	{
		read_values();
		line_follow();
	}
	 if(count==1)
	 {
		 forward_mm(50);
		 stop();
		 _delay_ms(100);
		 right_degrees(80);
		 for (int i=0;i<4000;i++)
		 {
			 LW = ADC_Conversion(3); //Getting data of Left WL Sensor
			 CW = ADC_Conversion(2); //Getting data of Center WL Sensor
			 R_W = ADC_Conversion(1); //Getting data of Right WL Sensor
			 
			 right();
			 velocity(200,200);
			 if(CW>=20)
			 break;
		 }
		 //back_mm(30);
		 line_follow();
	 }			
	 if(count==2)
	 {
		 forward_mm(60);
		 stop();
		 _delay_ms(100);
		 left_degrees(85);
		 for (int i=0;i<4000;i++)
		 {
			 LW = ADC_Conversion(3); //Getting data of Left WL Sensor
			 CW = ADC_Conversion(2); //Getting data of Center WL Sensor
			 R_W = ADC_Conversion(1); //Getting data of Right WL Sensor
			 
			 left();
			 velocity(200,200);
			 if(CW>=20)
			 break;
		 }
		 //back_mm(30);
		 line_follow();
	 }
	 if(count==3)
	 {
		 forward_mm(50);
		 stop();
		 _delay_ms(100);
		 right_degrees(70);
		 for (int i=0;i<4000;i++)
		 {
			 LW = ADC_Conversion(3); //Getting data of Left WL Sensor
			 CW = ADC_Conversion(2); //Getting data of Center WL Sensor
			 R_W = ADC_Conversion(1); //Getting data of Right WL Sensor
			 
			 right();
			 velocity(200,200);
			 if(CW>=20)
			 break;
		 }
		 //back_mm(30);
		 forward_mm_follow(120);
		 //green_detect();
		 left_degrees(170);
		 for (int i=0;i<4000;i++)
		 {
			 LW = ADC_Conversion(3); //Getting data of Left WL Sensor
			 CW = ADC_Conversion(2); //Getting data of Center WL Sensor
			 R_W = ADC_Conversion(1); //Getting data of Right WL Sensor
			 
			 left();
			 velocity(200,200);
			 if(CW>=20)
			 break;
		 }
		 line_follow();
		 
	 }
	 if(count==4)
	 {
		 forward_mm(50);
		 stop();
		 _delay_ms(100);
		 left_degrees(40);
		 for (int i=0;i<4000;i++)
		 {
			 LW = ADC_Conversion(3); //Getting data of Left WL Sensor
			 CW = ADC_Conversion(2); //Getting data of Center WL Sensor
			 R_W = ADC_Conversion(1); //Getting data of Right WL Sensor
			 
			 left();
			 velocity(200,200);
			 if(CW>=20)
			 break;
		 }
		 //back_mm(30);
		 line_follow();
	 }
	 if(count==5)
	 {
		 forward_mm(50);
		 stop();
		 _delay_ms(100);
		 right_degrees(60);
		 for (int i=0;i<4000;i++)
		 {
			 LW = ADC_Conversion(3); //Getting data of Left WL Sensor
			 CW = ADC_Conversion(2); //Getting data of Center WL Sensor
			 R_W = ADC_Conversion(1); //Getting data of Right WL Sensor
			 
			 right();
			 velocity(200,200);
			 if(CW>=20)
			 break;
		 }
		 //back_mm(30);
		 //forward_mm(50);
		 line_follow();
	 }
	 if(count==6)
	 {
		 forward_mm(50);
		 stop();
		 _delay_ms(100);
		 left_degrees(80);
		 for (int i=0;i<4000;i++)
		 {
			 LW = ADC_Conversion(3); //Getting data of Left WL Sensor
			 CW = ADC_Conversion(2); //Getting data of Center WL Sensor
			 R_W = ADC_Conversion(1); //Getting data of Right WL Sensor
			 
			 left();
			 velocity(200,200);
			 if(CW>=20)
			 break;
		 }
		 line_follow();
	 }		 
	 if (count==7)
	 {
		 //forward_mm(50);
		 stop();
		 
	 }
}
void grab()
{
	for (int i = 10; i<=180; i++)
	{
		servo_2(i);
		_delay_ms(30);
	}
	for (int i = 120; i<=160; i++)
	{
		servo_1(i);
		_delay_ms(30);
	}
	for ( int i = 180; i>=10; i--)
	{
		servo_2(i);
		_delay_ms(30);		
	}
}
void release()
{
	for (int p = 90; p<=180; p++)
	{
		servo_2(p);
		_delay_ms(30);
	}
	for (int p = 160;p>=120; p--)
	{
		servo_1(p);
		_delay_ms(30);	
	}

	for ( int p = 180; p>=90; p--)
	{
		servo_2(p);
		_delay_ms(30);		
	}
}			
void inside_room()
{
	 if(count==0)
	 {
		 read_values();
		 line_follow();
	 }
	 if(count==1)
	 {
		 forward_mm(50);
		 stop();
		 _delay_ms(100);
		 right_degrees(90);
		 for (int i=0;i<4000;i++)
		 {
			 LW = ADC_Conversion(3); //Getting data of Left WL Sensor
			 CW = ADC_Conversion(2); //Getting data of Center WL Sensor
			 R_W = ADC_Conversion(1); //Getting data of Right WL Sensor
			 
			 right();
			 velocity(200,200);
			 if(CW>=20)
			 break;
		 }
		 //back_mm(30);
		 //forward_mm(60);
		 for (int i=0;i<40;i++)
		 {
			 sharp3 = ADC_Conversion(11);
			 value3 = Sharp_GP2D12_estimation(sharp3);
		 }
		 if(value3<350)
		 {
			 forward_mm_follow(30);
			 grab();
		 }
		 else
		 {
			 forward_mm_follow(30);
			 release();
		 }
		 back_mm(10);
		 left_degrees(170);
		 for (int i=0;i<4000;i++)
		 {
			 LW = ADC_Conversion(3); //Getting data of Left WL Sensor
			 CW = ADC_Conversion(2); //Getting data of Center WL Sensor
			 R_W = ADC_Conversion(1); //Getting data of Right WL Sensor
			 
			 left();
			 velocity(200,200);
			 if(CW>=20)
			 break;
		 }
		 
		 stop();
		 _delay_ms(100);
		 //forward_mm(120);
		 for (int i=0;i<40;i++)
		 {
			 sharp3 = ADC_Conversion(11);
			 value3 = Sharp_GP2D12_estimation(sharp3);
		 }
		 if(value3<350)
		 {
			 forward_mm_follow(30);
			 grab();
			 back_mm(30);
		 }
		 left_degrees(70);
		 for (int i=0;i<4000;i++)
		 {
			 LW = ADC_Conversion(3); //Getting data of Left WL Sensor
			 CW = ADC_Conversion(2); //Getting data of Center WL Sensor
			 R_W = ADC_Conversion(1); //Getting data of Right WL Sensor
			 
			 left();
			 velocity(200,200);
			 if(R_W>=20)
			 break;
		 }
		 line_follow();
	 }

	 if(count==2)
	 {
		 forward_mm(50);
		 stop();
		 _delay_ms(100);
		 line_follow();
		 
	 }
}
int main(void)
{
    init_devices();
	port_init();
    lcd_set_4bit();
    lcd_init();
	RGB_LED_config();
	color_sensor_scaling();
	for(int i=0;i<=20;i++)
	{
		sharp3 = ADC_Conversion(11);
		value3 = Sharp_GP2D12_estimation(sharp3);
	}
	forward_mm_follow(250);
	while(1)
    {
		
		//red_detect();
	Left_white_line = ADC_Conversion(3);	//Getting data of Left WL Sensor
	Center_white_line = ADC_Conversion(2);	//Getting data of Center WL Sensor
	Right_white_line = ADC_Conversion(1);	//Getting data of Right WL Sensor
	sharp2 = ADC_Conversion(13);
	value2 = Sharp_GP2D12_estimation(sharp2);
	lcd_print(1,2,value2,3);
	sharp1 = ADC_Conversion(9);						//Stores the Analog value of front sharp connected to ADC channel 11 into variable "sharp"
	value1 = Sharp_GP2D12_estimation(sharp1);
	
	mapping_arena();
	//inside_room();
	//green_service();
	forward_mm_follow(50);
	//left_degrees(30);
      //line_follow_forward();
	  //line_follow_backward();
	 //right_side_service();
	 //lcd_print(1,1,room_color[0],1);
	 //lcd_print(1,3,room_color[1],1);
	 //lcd_print(1,5,room_color[2],1);
	 //lcd_print(1,7,room_color[3],1);
	 //lcd_print(1,9,room_color[4],1);
	 //lcd_print(1,11,room_color[5],1);
	 
}	
			
		 }